name: RCE
on:
  push:
    branches:
      - "main"
jobs:
  test-build:
    name: docker-push
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: nodev14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install
        run: npm install
      - name: test
        run: npm run test
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push
        shell: bash
        run: |
          TAG=ghcr.io/bhautikchudasama/rce:${GITHUB_REF##*/}-${GITHUB_SHA:0:7}-$(date +%s)
          docker build -t ${TAG} .
          docker push ${TAG}
